// Generated by ReScript, PLEASE EDIT WITH CARE


let Event = {};

function subscribe(premise_id) {
  let url = new URL(process.env.API_BASE_URL + `/events?premise_id=` + premise_id);
  url.protocol = "ws";
  let ws = new WebSocket(url.href);
  ws.onmessage = (_ws, event) => {
    console.log("Received message");
    console.log(event);
  };
}

let Client = {
  subscribe: subscribe
};

export {
  Event,
  Client,
}
/* No side effect */
