// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib from "@rescript/runtime/lib/es6/Stdlib.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as PgtypedRescriptRuntime from "pgtyped-rescript-runtime";

let query1IR = {"usedParamSet":{},"params":[],"statement":"LISTEN test"};

let query = new PgtypedRescriptRuntime.PreparedQuery(query1IR);

function many(client, params) {
  return query.run(params, client);
}

async function one(client, params) {
  let match = await query.run(params, client);
  if (match.length !== 1) {
    return;
  } else {
    return Primitive_option.some(match[0]);
  }
}

async function expectOne(client, params, errorMessage) {
  let match = await query.run(params, client);
  if (match.length !== 1) {
    return Stdlib.panic(Stdlib_Option.getOr(errorMessage, "More or less than one item was returned"));
  } else {
    return match[0];
  }
}

async function execute(client, params) {
  await query.run(params, client);
}

let Query1 = {
  many: many,
  one: one,
  expectOne: expectOne,
  execute: execute
};

function query1(params, client) {
  return query.run(params, client);
}

export {
  Query1,
  query1,
}
/* query Not a pure module */
