// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Bun from "bun";

let dbConfig = process.env.DB_URL;

let client = new $$Bun.SQL(dbConfig);

async function getClient() {
  return client;
}

async function withClient(fn) {
  let client = await getClient();
  let result = fn(client);
  return await result.then(result => client.end().then(() => Promise.resolve(result)));
}

export {
  dbConfig,
  client,
  getClient,
  withClient,
}
/* dbConfig Not a pure module */
