// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pg from "pg";

let dbConfig = process.env.DB_URL;

let pool = new Pg.Pool({
  max: 100,
  connectionString: dbConfig
});

async function getClient() {
  return await pool.connect();
}

async function withClient(fn) {
  let client = await getClient();
  let result = fn(client);
  return await result.then(result => Promise.resolve(client.release()).then(param => Promise.resolve(result)));
}

export {
  dbConfig,
  pool,
  getClient,
  withClient,
}
/* dbConfig Not a pure module */
