// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

async function getInventoryList(client, premise_id) {
  return await client([
    `
  SELECT i.*, JSONB_AGG(TO_JSONB(p.*)) as period_list FROM inventory i
  JOIN inventory_period_map pm ON pm.inventory_id = i.id
  JOIN period p ON p.id = pm.period_id
  WHERE premise_id = `,
    `
  GROUP BY i.id, i.premise_id, i.name, i.description, i.quantity
  `
  ], [premise_id]);
}

function toInventoryItem(row) {
  let periods = row.period_list;
  let period_list = periods !== undefined ? Primitive_option.valFromOption(periods) : [];
  return {
    description: row.description,
    id: row.id,
    name: row.name,
    quantity: row.quantity,
    premise_id: row.premise_id,
    period_list: period_list
  };
}

export {
  getInventoryList,
  toInventoryItem,
}
/* No side effect */
