// Generated by ReScript, PLEASE EDIT WITH CARE

import PgPromise from "pg-promise";
import * as PgListener from "pg-listener";

function make() {
  if (globalThis.pgOptions) {
    return globalThis.pgListener;
  }
  let pgp = PgPromise();
  let db = pgp(process.env.DB_URL);
  let pgOptions = {
    pgp: pgp,
    db: db
  };
  globalThis.pgOptions = pgOptions;
  globalThis.pgListener = new PgListener.PgListener(pgOptions);
  return globalThis.pgListener;
}

let Singleton = {
  make: make
};

function withListener(premise_id, onMessage) {
  let pgListener = make();
  pgListener.listen([premise_id], {
    onMessage: onMessage
  });
}

export {
  Singleton,
  withListener,
}
/* pg-promise Not a pure module */
