// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Stdlib_Nullable from "@rescript/runtime/lib/es6/Stdlib_Nullable.js";
import * as Inventory$Executor from "./Inventory.mjs";
import * as Premise__sql$Executor from "./Premise__sql.mjs";

async function getPremise(client, premise_id) {
  let query = Premise__sql$Executor.Query1.one;
  return Stdlib_Nullable.fromOption(await query(client, {
    premise_id: premise_id
  }));
}

async function getConfig(client, premise_id, url) {
  let inventoryRows = await Inventory$Executor.getInventoryList(client, premise_id);
  let inventory = Belt_Array.map(inventoryRows, Inventory$Executor.toInventoryItem);
  let match = url.pathname;
  let url$1 = match === "/" ? ({
      hd: "/",
      tl: /* [] */0
    }) : Stdlib_List.fromArray(url.pathname.split("/"));
  return {
    inventory: inventory,
    appUrl: url$1
  };
}

export {
  getPremise,
  getConfig,
}
/* Inventory-Executor Not a pure module */
