// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Route__sql$Executor from "./Route__sql.mjs";

async function getMatchingPremise(client, _root) {
  let query = Route__sql$Executor.Query1.one;
  return await query(client, undefined);
}

export {
  getMatchingPremise,
}
/* Route__sql-Executor Not a pure module */
