// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Route__sql$Executor from "./Route__sql.mjs";

async function getMatchingPremise(client, root) {
  console.log("Looking up root route:" + root);
  let query = Route__sql$Executor.Query1.one;
  return Stdlib_Option.getOrThrow(await query(client, {
    root: root
  }), "Invalid route root:" + root).premise_id;
}

export {
  getMatchingPremise,
}
/* Route__sql-Executor Not a pure module */
