// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../Ui/Card.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function NotFound(props) {
  return JsxRuntime.jsx(Card.make, {
    children: JsxRuntime.jsx("h1", {
      children: "Not Found"
    })
  });
}

let make = NotFound;

export {
  make,
}
/* Card Not a pure module */
