// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "@tilia/tilia/src/Tilia.mjs";
import * as React from "react";
import * as Webapi__Fetch from "rescript-webapi/src/Webapi/Webapi__Fetch.mjs";

let base_url = import.meta.env.VITE_API_BASE_URL;

async function fetch$1(premiseId) {
  let response = await fetch(base_url + `/config/` + premiseId, Webapi__Fetch.RequestInit.make("Get", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
  return JSON.parse(await response.text());
}

let empty = {
  inventory: []
};

let context = React.createContext(empty);

let provider = context.Provider;

function PremiseContainer$SSR$Provider(props) {
  return React.createElement(provider, {
    value: props.value,
    children: props.children
  });
}

let premiseId = "a55351b1-1b78-4b6c-bd13-6859dc9ad410";

let domExecutorConfig = ((typeof window !== 'undefined' ? window.__EXECUTOR_CONFIG__ ?? null : null));

let initialExecutorConfig = (domExecutorConfig == null) ? empty : domExecutorConfig;

let state = Tilia.source(initialExecutorConfig, async (_prev, set) => {
  let config = await fetch$1(premiseId);
  set(config);
  return setInterval(() => {
    fetch$1(premiseId).then(config => Promise.resolve(set(config)));
  }, 5000);
});

let Config = {
  fetch: fetch$1
};

let SSR_Provider = {
  make: PremiseContainer$SSR$Provider
};

let SSR = {
  empty: empty,
  context: context,
  Provider: SSR_Provider
};

export {
  Config,
  SSR,
  state,
}
/* base_url Not a pure module */
