// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "@tilia/tilia/src/Tilia.js";
import * as PeriodList from "./PeriodList.js";
import * as PremiseContainer from "./PremiseContainer.js";

let match = Tilia.signal("hour");

let signal = match[0];

let Unit_set = match[1];

let Unit = {
  defaultState: "hour",
  signal: signal,
  set: Unit_set
};

let main_store = Tilia.carve(param => ({
  config: PremiseContainer.state,
  period_list: param.derived(PeriodList.deriveState),
  unit: Tilia.lift(signal)
}));

export {
  Unit,
  main_store,
}
/* match Not a pure module */
