hoist: true

ignoredBuiltDependencies:
  - '@scarf/scarf'
  - esbuild
  - rescript
  - rescript-embed-lang

onlyBuiltDependencies:
  - '@rolandpeelen/rewatch'
  - bun
  - rescript-embed-lang

workspaces:
  - executor/*
  - executor-ui/*
