ignoredBuiltDependencies:
  - '@scarf/scarf'
  - esbuild
  - rescript
  - rescript-embed-lang

onlyBuiltDependencies:
  - '@rolandpeelen/rewatch'
  - bun

workspaces:
  - executor/*
  - executor-ui/*
