// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function formatCurrency(amount, locale, currency) {
  let locale_ = Belt_Option.getWithDefault(locale, "en-US");
  let currency_ = Belt_Option.getWithDefault(currency, "USD");
  let formatter = Intl.NumberFormat(locale_, {
    style: "currency",
    currency: currency_
  });
  return formatter.format(amount);
}

export {
  formatCurrency,
}
/* No side effect */
