// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pg from "pg";

function getClient() {
  return new Pg.Client("postgres://executor:executor-password@localhost/executor_db");
}

export {
  getClient,
}
/* pg Not a pure module */
