// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Connection from "./Connection.js";
import * as Inventory__sql from "./Inventory__sql.js";

async function getInventoryList() {
  let query = Inventory__sql.Query1.many;
  let client = await Connection.getClient();
  return await query(client, undefined);
}

export {
  getInventoryList,
}
/* Connection Not a pure module */
