// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Inventory__sql from "./Inventory__sql.js";

async function getInventoryList(client, premise_id) {
  let query = Inventory__sql.Query1.many;
  return await query(client, {
    premise_id: premise_id
  });
}

export {
  getInventoryList,
}
/* Inventory__sql Not a pure module */
