// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Premise__sql from "./Premise__sql.mjs";
import * as Stdlib_Nullable from "@rescript/runtime/lib/es6/Stdlib_Nullable.js";

async function getPremise(client, premise_id) {
  let query = Premise__sql.Query1.one;
  return Stdlib_Nullable.fromOption(await query(client, {
    premise_id: premise_id
  }));
}

export {
  getPremise,
}
/* Premise__sql Not a pure module */
