// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tenant__sql from "./Tenant__sql.js";
import * as Stdlib_Nullable from "@rescript/runtime/lib/es6/Stdlib_Nullable.js";

async function getTenant(client, tenantId) {
  let query = Tenant__sql.Query1.one;
  return Stdlib_Nullable.fromOption(await query(client, {
    tenantId: tenantId
  }));
}

export {
  getTenant,
}
/* Tenant__sql Not a pure module */
