// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Store$ExecutorUi from "../State/Store.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function str(prim) {
  return prim;
}

function itemCount(state) {
  return state.length;
}

let context = React.createContext(_action => {});

let provider = context.Provider;

function Cart$DispatchContext$Provider(props) {
  return React.createElement(provider, {
    value: props.value,
    children: props.children
  });
}

let Provider = {
  provider: provider,
  make: Cart$DispatchContext$Provider
};

let DispatchContext = {
  context: context,
  Provider: Provider
};

let state_cart = [];

let state_items = [];

let state = {
  cart: state_cart,
  selected_item: undefined,
  items: state_items
};

let context$1 = React.createContext(state);

let provider$1 = context$1.Provider;

function Cart$StateContext$Provider(props) {
  return React.createElement(provider$1, {
    value: props.value,
    children: props.children
  });
}

let Provider$1 = {
  provider: provider$1,
  make: Cart$StateContext$Provider
};

let StateContext = {
  state: state,
  context: context$1,
  Provider: Provider$1
};

function Cart(props) {
  React.useContext(context$1);
  React.useContext(context);
  Store$ExecutorUi.getStore();
  return JsxRuntime.jsxs("h1", {
    children: [
      JsxRuntime.jsx("span", {
        children: JsxRuntime.jsx("i", {
          className: "light-icon-shopping-cart"
        }),
        className: "m-2 align-middle text-3xl font-light"
      }),
      "Selected equipment (",
      String(props.count),
      ")"
    ],
    className: "block font-bold align-middle text-gray-700 text-base m-2 text-3xl"
  });
}

let make = Cart;

export {
  str,
  itemCount,
  DispatchContext,
  StateContext,
  make,
}
/* context Not a pure module */
