// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";
import ReactDatePickerShimMjs from "../../../../src/shims/reactDatePickerShim.mjs";

import "react-datepicker/dist/react-datepicker.css"
;

let make = ReactDatePickerShimMjs;

let Raw = {
  make: make
};

function DatePicker(props) {
  let match = React.useState(() => false);
  let setIsClient = match[1];
  React.useEffect(() => {
    setIsClient(param => true);
  }, []);
  if (match[0]) {
    return JsxRuntime.jsx(make, {
      calendarClassName: props.calendarClassName,
      className: props.className,
      isOpen: props.isOpen,
      minDate: props.minDate,
      onChange: props.onChange,
      selected: props.selected
    });
  } else {
    return null;
  }
}

let make$1 = DatePicker;

export {
  Raw,
  make$1 as make,
}
/*  Not a pure module */
