// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LucideReact from "lucide-react";
import * as JsxRuntime from "react/jsx-runtime";

let Calendar = {
  make: LucideReact.Calendar
};

let Clock = {
  make: LucideReact.Clock
};

let MonitorCloud = {
  make: LucideReact.MonitorCloud
};

let Cloud = {
  make: LucideReact.Cloud
};

let SearchIcon = {
  make: LucideReact.SearchIcon
};

function Icon$IconButton(props) {
  return JsxRuntime.jsx("button", {
    children: JsxRuntime.jsx(props.icon.make, {
      size: 16,
      color: "white"
    })
  });
}

let IconButton = {
  make: Icon$IconButton
};

JsxRuntime.jsx(Icon$IconButton, {
  icon: Cloud
});

export {
  Calendar,
  Clock,
  MonitorCloud,
  Cloud,
  SearchIcon,
  IconButton,
}
/* Calendar Not a pure module */
