// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";
import * as Store$ExecutorUi from "../State/Store.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as PeriodList$ExecutorUi from "../State/PeriodList.mjs";

function str(prim) {
  return prim;
}

let make = TiliaReact.leaf(props => {
  let main_store = Store$ExecutorUi.getStore();
  return JsxRuntime.jsx("div", {
    children: main_store.period_list.map(period => JsxRuntime.jsxs("label", {
      children: [
        JsxRuntime.jsx("input", {
          className: "m-1",
          id: `type_` + period.unit,
          autoComplete: "off",
          checked: main_store.unit === period.unit,
          name: "type",
          type: "radio",
          value: "hour",
          onChange: e => {
            let inputEl = e.currentTarget;
            if (inputEl.checked !== true) {
              return;
            }
            let match = period.unit;
            switch (match) {
              case "day" :
                return PeriodList$ExecutorUi.Unit.set("day");
              case "hour" :
                return PeriodList$ExecutorUi.Unit.set("hour");
              case "minute" :
                return PeriodList$ExecutorUi.Unit.set("minute");
              case "month" :
                return PeriodList$ExecutorUi.Unit.set("month");
              case "second" :
                return PeriodList$ExecutorUi.Unit.set("second");
              case "week" :
                return PeriodList$ExecutorUi.Unit.set("week");
              case "year" :
                return PeriodList$ExecutorUi.Unit.set("year");
              default:
                return PeriodList$ExecutorUi.Unit.set(PeriodList$ExecutorUi.Unit.defaultState);
            }
          }
        }),
        JsxRuntime.jsx("span", {
          children: period.label,
          className: "p-1 pl-0"
        })
      ],
      className: "block",
      htmlFor: `type_` + period.unit
    }, period.unit)),
    className: "my-auto"
  });
});

export {
  str,
  make,
}
/* make Not a pure module */
