// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../Ui/Card.mjs";
import * as Icon from "../Ui/Icon.mjs";
import * as State from "../State/State.mjs";
import * as Belt_Id from "@rescript/runtime/lib/es6/Belt_Id.js";
import * as Js_array from "@rescript/runtime/lib/es6/Js_array.js";
import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";
import * as InventoryItem from "../InventoryItem/InventoryItem.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as JsxRuntime from "react/jsx-runtime";

function str(prim) {
  return prim;
}

let cmp = Primitive_object.compare;

let IntCmp = Belt_Id.MakeComparable({
  cmp: cmp
});

let make = TiliaReact.leaf(props => {
  let closeDate = props.closeDate;
  let openDate = props.openDate;
  let config = State.main_store.config;
  let unit = State.main_store.unit;
  let items = config.inventory;
  let filterType = "all";
  let now = new Date();
  let today = new Date(now.setHours(0.0, 0.0, 0.0, 0.0));
  let openDate$1 = openDate !== undefined ? openDate : today;
  let closeDate$1 = closeDate !== undefined ? closeDate : today;
  let heading = unit !== "hour" && Primitive_object.notequal(openDate$1, closeDate$1) ? "Showing " + filterType + " equipment available from " + openDate$1.toLocaleDateString() + " to " + closeDate$1.toLocaleDateString() : "Showing " + filterType + " equipment available " + (
      Primitive_object.equal(openDate$1, today) ? "today" : openDate$1.toLocaleDateString()
    );
  return JsxRuntime.jsxs(Card.make, {
    children: [
      JsxRuntime.jsxs("h1", {
        children: [
          JsxRuntime.jsx(Icon.SearchIcon.make, {
            size: 48,
            className: "text-slate-400 mr-2 my-auto inline content-start"
          }),
          JsxRuntime.jsx("span", {
            children: heading,
            className: "align-middle"
          })
        ],
        className: "block align-middle text-lg content-center"
      }),
      JsxRuntime.jsx(Card.make, {
        children: Js_array.map(item => {
          let match = item.period_list.find(pl => pl.unit === unit);
          if (match !== undefined) {
            return JsxRuntime.jsx(InventoryItem.make, {
              item: item
            }, String(item.id));
          } else {
            return null;
          }
        }, items),
        className: "border-none shadow-none shadow-transparent m-0 p-0 place-content-start grid lg:grid-cols-8 grid-cols-4 gap-4"
      })
    ],
    className: "m-0 p-0 bg-white/30 border-2 border-b-4 border-r-4 border-gray-200/60"
  });
});

export {
  str,
  IntCmp,
  make,
}
/* IntCmp Not a pure module */
