"use client"
// Generated by ReScript, PLEASE EDIT WITH CARE


let Event = {};

function subscribe(premise_id, set) {
  console.log("Connecting to WebSocket server");
  let url = new URL(process.env.API_BASE_URL + `/events?premise_id=` + premise_id);
  url.protocol = "ws";
  let ws = new WebSocket(url.href);
  ws.addEventListener("message", event => {
    console.log(event);
  }, true);
}

let Client = {
  subscribe: subscribe
};

export {
  Event,
  Client,
}
/* No side effect */
