// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_array from "@rescript/runtime/lib/es6/Js_array.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";
import * as Card$ExecutorUi from "../Ui/Card.mjs";
import * as Cart$ExecutorUi from "../Cart/Cart.mjs";
import * as Icon$ExecutorUi from "../Ui/Icon.mjs";
import * as State$ExecutorUi from "../State/State.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as Container$ExecutorUi from "../Ui/Container.mjs";
import * as InventoryList$ExecutorUi from "../InventoryList/InventoryList.mjs";
import * as ReservationTypeSelection$ExecutorUi from "../ReservationTypeSelection/ReservationTypeSelection.mjs";

function str(prim) {
  return prim;
}

function addToCart(state, id) {
  return {
    cart: Belt_Array.concat(state.cart, [id]),
    selected_item: state.selected_item,
    items: state.items
  };
}

function removeFromCart(state, id) {
  return {
    cart: Js_array.filter(compareId => compareId !== id, state.cart),
    selected_item: state.selected_item,
    items: state.items
  };
}

let make = TiliaReact.leaf(props => {
  State$ExecutorUi.getStore();
  let today = new Date();
  today.setHours(0, 0, 0, 0);
  let match = React.useState(() => today);
  let openDate = match[0];
  let match$1 = React.useState(() => today);
  let closeDate = match$1[0];
  React.useEffect(() => {
    console.log("Open Date:");
    console.log(openDate);
    console.log("Close Date:");
    console.log(closeDate);
    return () => {};
  }, [
    openDate,
    closeDate
  ]);
  let match$2 = React.useReducer((state, action) => {
    console.log("calling reducer");
    console.log({
      state: state,
      action: action
    });
    let result;
    result = action.TAG === "AddToCart" ? addToCart(state, action.id) : removeFromCart(state, action.id);
    console.log({
      nextState: result
    });
    return result;
  }, {
    cart: [],
    selected_item: undefined,
    items: []
  });
  let state = match$2[0];
  let cartCount = state.cart.length;
  return JsxRuntime.jsxs(Container$ExecutorUi.make, {
    children: [
      JsxRuntime.jsx(Card$ExecutorUi.make, {
        children: JsxRuntime.jsx("h1", {
          children: JsxRuntime.jsxs("span", {
            children: [
              JsxRuntime.jsx(Icon$ExecutorUi.MonitorCloud.make, {
                size: 48,
                className: "text-slate-400 mr-2 my-auto inline content-start"
              }),
              "Cloud Hardware Rental"
            ]
          }),
          className: "text-xl"
        }),
        className: "bg-slate-200/40 border-slate-200/40 border-1"
      }),
      JsxRuntime.jsxs(Card$ExecutorUi.make, {
        children: [
          JsxRuntime.jsxs("span", {
            children: [
              JsxRuntime.jsx(Icon$ExecutorUi.Clock.make, {
                size: 48,
                className: "text-slate-400 mr-2 my-auto inline content-start"
              }),
              "Select your reservation type: "
            ],
            className: "align-middle text-lg"
          }),
          JsxRuntime.jsx(ReservationTypeSelection$ExecutorUi.make, {}),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx(Icon$ExecutorUi.Calendar.make, {
                size: 48,
                className: "absolute left-0 top-0 bottom-0 my-auto text-slate-400"
              }),
              JsxRuntime.jsx("span", {
                children: "Select your reservation start date: ",
                className: "align-middle text-lg pl-[56px]"
              }),
              JsxRuntime.jsx("input", {
                className: "block align-end outline-slate-400 outline-1 px-2"
              }),
              JsxRuntime.jsx("span", {
                children: "Select your reservation end date: ",
                className: "align-middle text-lg pl-[56px]"
              }),
              JsxRuntime.jsx("input", {
                className: "block align-end outline-slate-400 outline-1 px-2"
              })
            ],
            className: "col-span-full grid grid-cols-subgrid relative"
          })
        ],
        className: "grid grid-cols-[auto_1fr] bg-white/20 gap-4 place-items-start items-center"
      }),
      JsxRuntime.jsx(Cart$ExecutorUi.StateContext.Provider.make, {
        children: JsxRuntime.jsxs(Cart$ExecutorUi.DispatchContext.Provider.make, {
          children: [
            JsxRuntime.jsx(InventoryList$ExecutorUi.make, {
              openDate: openDate,
              closeDate: closeDate
            }),
            JsxRuntime.jsx(Cart$ExecutorUi.make, {
              count: cartCount
            })
          ],
          value: match$2[1]
        }),
        value: state
      }),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx("button", {
          children: "Book Reservation",
          className: "mx-auto mt-4 bg-slate-500 hover:bg-slate-700 text-white py-2 px-4 rounded-sm"
        }),
        className: "w-full"
      })
    ]
  });
});

export {
  str,
  addToCart,
  removeFromCart,
  make,
}
/* make Not a pure module */
