// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card$ExecutorUi from "../Ui/Card.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function NotFound(props) {
  return JsxRuntime.jsx(Card$ExecutorUi.make, {
    children: JsxRuntime.jsx("h1", {
      children: "Not Found"
    })
  });
}

let make = NotFound;

export {
  make,
}
/* Card-ExecutorUi Not a pure module */
