// Generated by ReScript, PLEASE EDIT WITH CARE


let base_url = process.env.API_BASE_URL;

async function fetch$1(premiseId) {
  let response = await fetch(base_url + `/config/` + premiseId, {
    method: "get"
  });
  return await response.json();
}

let empty_inventory = [];

let empty = {
  inventory: empty_inventory,
  premise: undefined
};

let SSR = {
  empty: empty
};

export {
  base_url,
  fetch$1 as fetch,
  SSR,
}
/* base_url Not a pure module */
