// Generated by ReScript, PLEASE EDIT WITH CARE


function toConfig(data) {
  let input = JSON.parse(data);
  let premise_id = input.premise.id;
  let premise_name = input.premise.name;
  let premise_description = input.premise.description;
  let premise_updated_at = new Date(input.premise.updated_at);
  let premise = {
    id: premise_id,
    name: premise_name,
    description: premise_description,
    updated_at: premise_updated_at
  };
  let inventory = input.inventory;
  return {
    inventory: inventory,
    premise: premise
  };
}

export {
  toConfig,
}
/* No side effect */
