// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let Premise = {};

let match = Tilia.signal("month");

let Unit_signal = match[0];

let Unit_set = match[1];

let Unit = {
  defaultState: "month",
  signal: Unit_signal,
  set: Unit_set
};

function deriveState(store) {
  let seen_units = new Set();
  let config = store.config;
  let inventory = config.inventory.slice(0);
  return Belt_Array.flatMap(inventory, inv => inv.period_list.map(pl => {
    if (seen_units.has(pl.unit)) {
      return;
    } else {
      seen_units.add(pl.unit);
      return Primitive_option.some(pl);
    }
  })).filter(pl => pl !== undefined).map(pl => pl);
}

export {
  Premise,
  Unit,
  deriveState,
}
/* match Not a pure module */
