// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function deriveState(store) {
  let seen_units = new Set();
  console.log("Config from store: ");
  console.log(store.config);
  let config = store.config;
  let inventory = config.inventory.slice(0);
  return Belt_Array.flatMap(inventory, inv => inv.period_list.map(pl => {
    if (seen_units.has(pl.unit)) {
      return;
    } else {
      seen_units.add(pl.unit);
      return Primitive_option.some(pl);
    }
  })).filter(pl => pl !== undefined).map(pl => pl);
}

export {
  deriveState,
}
/* No side effect */
