// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Client$ExecutorUi from "./Client.mjs";
import * as Config$ExecutorUi from "./Config.mjs";

let window = globalThis.window;

let window$1 = (window == null) ? ({
    __EXECUTOR_CONFIG__: null
  }) : window;

let domExecutorConfig = window$1.__EXECUTOR_CONFIG__;

let initialExecutorConfig;

if (domExecutorConfig == null) {
  initialExecutorConfig = Config$ExecutorUi.SSR.empty;
} else {
  let premise = domExecutorConfig.premise;
  let tmp;
  tmp = (premise == null) ? Config$ExecutorUi.SSR.empty.premise : ({
      id: premise.id,
      name: premise.name,
      description: premise.description,
      updated_at: new Date(premise.updated_at)
    });
  initialExecutorConfig = {
    inventory: domExecutorConfig.inventory,
    premise: tmp
  };
}

let state = Tilia.source(initialExecutorConfig, async (_prev, set) => {
  let premise = initialExecutorConfig.premise;
  if (premise === undefined) {
    return;
  }
  let match = globalThis.window;
  if (!(match == null)) {
    return Client$ExecutorUi.subscribe(premise.id, premise.updated_at.getTime(), set);
  }
});

export {
  state,
}
/* window Not a pure module */
