// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Nodeasync_hooks from "node:async_hooks";
import * as PeriodList$ExecutorUi from "./PeriodList.mjs";
import * as PremiseContainer$ExecutorUi from "./PremiseContainer.mjs";

let match = Tilia.signal("month");

let signal = match[0];

let Unit_set = match[1];

let Unit = {
  defaultState: "month",
  signal: signal,
  set: Unit_set
};

let storage = new Nodeasync_hooks.AsyncLocalStorage();

let window = globalThis.window;

function makeServerStore(initialExecutorConfig, callback) {
  if (!(window == null)) {
    return Stdlib_JsError.throwWithMessage("This function should never run in the client context");
  }
  console.log("makeServerStore initialConfig:");
  console.log(initialExecutorConfig);
  let store = Tilia.carve(param => ({
    config: initialExecutorConfig,
    period_list: param.derived(PeriodList$ExecutorUi.deriveState),
    unit: Tilia.lift(signal)
  }));
  return storage.run(store, callback);
}

function getServerStore() {
  return storage.getStore();
}

let main_store = !(window == null) ? Primitive_option.some(Tilia.carve(param => ({
    config: PremiseContainer$ExecutorUi.state,
    period_list: param.derived(PeriodList$ExecutorUi.deriveState),
    unit: Tilia.lift(signal)
  }))) : undefined;

function getStore() {
  if (main_store !== undefined) {
    return Primitive_option.valFromOption(main_store);
  } else {
    return storage.getStore();
  }
}

let window$1 = (window == null) ? undefined : Primitive_option.some(window);

export {
  Unit,
  storage,
  window$1 as window,
  makeServerStore,
  getServerStore,
  main_store,
  getStore,
}
/* match Not a pure module */
