// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Nodeasync_hooks from "node:async_hooks";
import * as PeriodList$ExecutorUi from "./PeriodList.mjs";
import * as PremiseContainer$ExecutorUi from "./PremiseContainer.mjs";

let match = Tilia.signal("month");

let signal = match[0];

let Unit_set = match[1];

let Unit = {
  defaultState: "month",
  signal: signal,
  set: Unit_set
};

let storage = new Nodeasync_hooks.AsyncLocalStorage();

function requestWithStore(req, callback) {
  let match = globalThis.window;
  if (!(match == null)) {
    return Stdlib_Exn.raiseError("This function should never run in the client context");
  }
  let store = Tilia.tilia({
    test: "Testing Tilia with AsyncLocalStorage on Bun. Request time: "
  });
  return storage.run(store, callback);
}

let main_store = Tilia.carve(param => ({
  config: PremiseContainer$ExecutorUi.state,
  period_list: param.derived(PeriodList$ExecutorUi.deriveState),
  unit: Tilia.lift(signal)
}));

export {
  Unit,
  storage,
  requestWithStore,
  main_store,
}
/* match Not a pure module */
