// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Nodeasync_hooks from "node:async_hooks";
import * as PeriodList$ExecutorUi from "./PeriodList.mjs";
import * as PremiseContainer$ExecutorUi from "./PremiseContainer.mjs";

let window = globalThis.window;

let storage = (window == null) ? Primitive_option.some(new Nodeasync_hooks.AsyncLocalStorage()) : undefined;

function derivePremiseId(store) {
  return Stdlib_Option.getOrThrow(store.config.premise, undefined).id;
}

function makeStore(initialExecutorConfig) {
  return Tilia.carve(param => {
    let derived = param.derived;
    return {
      premise_id: derived(derivePremiseId),
      config: initialExecutorConfig,
      period_list: derived(PeriodList$ExecutorUi.deriveState),
      unit: Tilia.lift(PeriodList$ExecutorUi.Unit.signal)
    };
  });
}

function makeServerStore(initialExecutorConfig, callback) {
  if (!(window == null)) {
    return Stdlib_JsError.throwWithMessage("This function should never run in the client context");
  }
  let store = makeStore(initialExecutorConfig);
  return storage.run(store, callback);
}

let main_store = !(window == null) ? Primitive_option.some(makeStore(PremiseContainer$ExecutorUi.state)) : undefined;

function getStore() {
  if (main_store !== undefined) {
    return Primitive_option.valFromOption(main_store);
  } else {
    return storage.getStore();
  }
}

export {
  getStore,
  makeServerStore,
}
/* window Not a pure module */
