// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pg from "pg";

async function getClient() {
  let client = new Pg.Client("postgres://executor:executor-password@localhost/executor_db");
  await client.connect();
  return client;
}

export {
  getClient,
}
/* pg Not a pure module */
