// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Connection from "./Connection.js";
import * as Inventory__sql from "./Inventory__sql.js";

async function getInventoryList() {
  let query = Inventory__sql.Query1.many;
  let client = await Connection.getClient();
  let result = await query(client, undefined);
  await client.end();
  return result;
}

export {
  getInventoryList,
}
/* Connection Not a pure module */
