// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Landing from "../Landing/Landing.js";
import * as ErrorView from "../ErrorView/ErrorView.js";
import * as PremiseContainer from "../State/PremiseContainer.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";

function getActiveId(url) {
  let match = url.path;
  if (match === 0) {
    return;
  }
  if (match.hd !== "item") {
    return;
  }
  let match$1 = match.tl;
  if (match$1 !== 0) {
    return match$1.hd;
  }
}

function App(props) {
  let initialExecutorConfig = props.initialExecutorConfig;
  let initialUrl = RescriptReactRouter.useUrl(props.serverUrl, undefined);
  let match = React.useState(() => initialUrl);
  let setUrl = match[1];
  React.useEffect(() => {
    let watcherID = RescriptReactRouter.watchUrl(newUrl => {
      console.log("URL changed to:", newUrl.path);
      setUrl(param => newUrl);
    });
    return () => RescriptReactRouter.unwatchUrl(watcherID);
  }, []);
  let executorConfigValue = initialExecutorConfig !== undefined ? initialExecutorConfig : PremiseContainer.SSR.empty;
  let match$1 = match[0].path;
  let tmp;
  tmp = match$1 !== 0 && match$1.hd !== "item" ? JsxRuntime.jsx(ErrorView.make, {}) : JsxRuntime.jsx(Landing.make, {});
  return JsxRuntime.jsx(PremiseContainer.SSR.Provider.make, {
    value: executorConfigValue,
    children: tmp
  });
}

let make = App;

export {
  getActiveId,
  make,
}
/* react Not a pure module */
