// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";
import * as Landing$ExecutorUi from "../Landing/Landing.mjs";
import * as NotFound$ExecutorUi from "../NotFound/NotFound.mjs";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.mjs";
import * as PremiseContainer$ExecutorUi from "../State/PremiseContainer.mjs";

function getActiveId(url) {
  let match = url.path;
  if (match === 0) {
    return;
  }
  if (match.hd !== "item") {
    return;
  }
  let match$1 = match.tl;
  if (match$1 !== 0) {
    return match$1.hd;
  }
}

function App(props) {
  let initialExecutorConfig = props.initialExecutorConfig;
  let initialUrl = RescriptReactRouter.useUrl(props.serverUrl, undefined);
  let match = React.useState(() => initialUrl);
  let setUrl = match[1];
  React.useEffect(() => {
    let watcherID = RescriptReactRouter.watchUrl(newUrl => setUrl(param => newUrl));
    return () => RescriptReactRouter.unwatchUrl(watcherID);
  }, []);
  let executorConfigValue = initialExecutorConfig !== undefined ? initialExecutorConfig : PremiseContainer$ExecutorUi.SSR.empty;
  let match$1 = match[0].path;
  let tmp;
  tmp = match$1 !== 0 && match$1.hd !== "item" ? JsxRuntime.jsx(NotFound$ExecutorUi.make, {}) : JsxRuntime.jsx(Landing$ExecutorUi.make, {});
  return JsxRuntime.jsx(PremiseContainer$ExecutorUi.SSR.Provider.make, {
    value: executorConfigValue,
    children: tmp
  });
}

let make = App;

export {
  getActiveId,
  make,
}
/* react Not a pure module */
