// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App/App.mjs";
import * as PremiseContainer from "./State/PremiseContainer.mjs";
import * as Server from "react-dom/server";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.mjs";

function render() {
  let appUrl = RescriptReactRouter.dangerouslyGetInitialUrl(`http://localhost:8899/`, undefined);
  return PremiseContainer.Config.fetch("a55351b1-1b78-4b6c-bd13-6859dc9ad410").then(config => {
    console.log("Fetched config: ");
    console.log(config);
    console.log("App URL:");
    console.log(appUrl);
    return Promise.resolve({
      executorConfig: config,
      html: Server.renderToString(JsxRuntime.jsx(App.make, {
        initialExecutorConfig: config,
        serverUrl: appUrl
      }))
    });
  });
}

export {
  render,
}
/* App Not a pure module */
