// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Inventory__sql from "./Inventory__sql.mjs";

async function getInventoryList(client, premise_id) {
  let query = Inventory__sql.Query1.many;
  return await query(client, {
    premise_id: premise_id
  });
}

function toInventoryItem(row) {
  let periods = row.period_list;
  let period_list = periods !== undefined ? periods : [];
  return {
    description: row.description,
    id: row.id,
    name: row.name,
    quantity: row.quantity,
    premise_id: row.premise_id,
    period_list: period_list
  };
}

export {
  getInventoryList,
  toInventoryItem,
}
/* Inventory__sql Not a pure module */
