// Generated by ReScript, PLEASE EDIT WITH CARE

import PgPromise from "pg-promise";
import * as PgListener from "pg-listener";

function withListener(premise_id, onMessage) {
  let pgp = PgPromise();
  let db = pgp(process.env.DB_URL);
  let listener = new PgListener.PgListener({
    pgp: pgp,
    db: db
  });
  listener.listen([premise_id], {
    onMessage: onMessage
  });
}

export {
  withListener,
}
/* pg-promise Not a pure module */
