// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Inventory from "./Inventory.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Premise__sql from "./Premise__sql.mjs";
import * as Stdlib_Nullable from "@rescript/runtime/lib/es6/Stdlib_Nullable.js";

async function getPremise(client, premise_id) {
  let query = Premise__sql.Query1.one;
  return Stdlib_Nullable.fromOption(await query(client, {
    premise_id: premise_id
  }));
}

async function getConfig(client, premise_id) {
  let inventoryRows = await Inventory.getInventoryList(client, premise_id);
  let inventory = Belt_Array.map(inventoryRows, Inventory.toInventoryItem);
  return {
    inventory: inventory
  };
}

export {
  getPremise,
  getConfig,
}
/* Inventory Not a pure module */
