// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "../../client/src/App/App.mjs";
import * as Premise from "./Database/Premise.mjs";
import * as Inventory from "./Database/Inventory.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Connection from "./Database/Connection.mjs";
import * as Server from "react-dom/server";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.mjs";

function render(url) {
  let appUrl = RescriptReactRouter.dangerouslyGetInitialUrl(url, undefined);
  let premiseId = "a55351b1-1b78-4b6c-bd13-6859dc9ad410";
  let toInventoryItem = row => {
    let periods = row.period_list;
    let period_list = periods !== undefined ? periods : [];
    return {
      description: row.description,
      id: row.id,
      name: row.name,
      quantity: row.quantity,
      premise_id: row.premise_id,
      period_list: period_list
    };
  };
  return Connection.withClient(client => Premise.getPremise(client, premiseId).then(result => Inventory.getInventoryList(client, premiseId)).then(inventoryRows => {
    let inventory = Belt_Array.map(inventoryRows, toInventoryItem);
    let config = {
      inventory: inventory
    };
    return Promise.resolve({
      executorConfig: config,
      html: Server.renderToString(JsxRuntime.jsx(App.make, {
        initialExecutorConfig: config,
        serverUrl: appUrl
      }))
    });
  }));
}

export {
  render,
}
/* App Not a pure module */
