// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";
import * as Landing$ExecutorUi from "../Landing/Landing.mjs";
import * as NotFound$ExecutorUi from "../NotFound/NotFound.mjs";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.mjs";

function getActiveId(url) {
  let match = url.path;
  if (match === 0) {
    return;
  }
  if (match.hd !== "item") {
    return;
  }
  let match$1 = match.tl;
  if (match$1 !== 0) {
    return match$1.hd;
  }
}

function App(props) {
  let initialUrl = RescriptReactRouter.useUrl(props.serverUrl, undefined);
  let match = React.useState(() => initialUrl);
  let setUrl = match[1];
  React.useEffect(() => {
    let watcherID = RescriptReactRouter.watchUrl(newUrl => setUrl(param => newUrl));
    return () => RescriptReactRouter.unwatchUrl(watcherID);
  }, []);
  let match$1 = match[0].path;
  let tmp;
  if (match$1 !== 0) {
    switch (match$1.hd) {
      case "item" :
        tmp = JsxRuntime.jsx(Landing$ExecutorUi.make, {});
        break;
      case "test" :
        tmp = match$1.tl !== 0 ? JsxRuntime.jsx(NotFound$ExecutorUi.make, {}) : JsxRuntime.jsx(Landing$ExecutorUi.make, {});
        break;
      default:
        tmp = JsxRuntime.jsx(NotFound$ExecutorUi.make, {});
    }
  } else {
    tmp = JsxRuntime.jsx(Landing$ExecutorUi.make, {});
  }
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
    children: tmp
  });
}

let make = App;

export {
  getActiveId,
  make,
}
/* react Not a pure module */
