// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Landing$ExecutorUi from "../Landing/Landing.mjs";
import * as NotFound$ExecutorUi from "../NotFound/NotFound.mjs";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.mjs";

function getActiveId(url) {
  let match = url.path;
  if (match === 0) {
    return;
  }
  if (match.hd !== "item") {
    return;
  }
  let match$1 = match.tl;
  if (match$1 !== 0) {
    return match$1.hd;
  }
}

function App(props) {
  let initial_url = RescriptReactRouter.useUrl(props.server_url, undefined);
  let match = React.useState(() => initial_url);
  let set_url = match[1];
  React.useEffect(() => {
    let watcher_id = RescriptReactRouter.watchUrl(new_url => set_url(param => new_url));
    return () => RescriptReactRouter.unwatchUrl(watcher_id);
  }, []);
  let route_root = Stdlib_Option.getWithDefault(props.route_root, "/");
  let route_root_list = Stdlib_List.fromArray(route_root.split("/"));
  let item_route = Stdlib_List.concat(route_root_list, {
    hd: "item",
    tl: /* [] */0
  });
  console.log(route_root, item_route);
  let match$1 = match[0].path;
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
    children: match$1 !== 0 ? JsxRuntime.jsx(Landing$ExecutorUi.make, {}) : JsxRuntime.jsx(NotFound$ExecutorUi.make, {})
  });
}

let make = App;

export {
  getActiveId,
  make,
}
/* react Not a pure module */
