"use client"
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "@tilia/tilia/src/Tilia.mjs";
import * as React from "react";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let base_url = process.env.API_BASE_URL;

async function fetch$1(premiseId) {
  let response = await fetch(base_url + `/config/` + premiseId, {
    method: "get"
  });
  let json = await response.json();
  return JSON.parse(JSON.stringify(json));
}

let empty = {
  inventory: []
};

let context = React.createContext(empty);

let provider = context.Provider;

function PremiseContainer$SSR$Provider(props) {
  return React.createElement(provider, {
    value: props.value,
    children: props.children
  });
}

let premiseId = "a55351b1-1b78-4b6c-bd13-6859dc9ad410";

let domExecutorConfig = ((typeof window !== 'undefined' ? window.__EXECUTOR_CONFIG__ ?? null : null));

let initialExecutorConfig = (domExecutorConfig == null) ? empty : domExecutorConfig;

let state = Tilia.source(initialExecutorConfig, async (_prev, set) => {
  let match = globalThis.window;
  if (match == null) {
    console.log("Not connecting to WebSocket");
    return;
  } else {
    console.log("Connecting to WebSocket server");
    let url = new URL(process.env.API_BASE_URL + `/events?premise_id=` + premiseId);
    url.protocol = "ws";
    let ws = new WebSocket(url.href);
    ws.addEventListener("open", event => {
      console.log("Connected to WebSocket");
      console.log(event);
    });
    ws.addEventListener("message", event => {
      let jsonR = event.data;
      let json = JSON.parse(jsonR);
      set({
        inventory: Stdlib_Option.getOr(Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_JSON.Decode.object(json), d => d["inventory"]), Stdlib_JSON.Decode.array), []).map(itemJson => itemJson)
      });
    });
    return;
  }
});

let Config = {
  fetch: fetch$1
};

let SSR_Provider = {
  make: PremiseContainer$SSR$Provider
};

let SSR = {
  empty: empty,
  context: context,
  Provider: SSR_Provider
};

export {
  Config,
  SSR,
  premiseId,
  state,
}
/* base_url Not a pure module */
