"use client"
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "@tilia/tilia/src/Tilia.mjs";
import * as PeriodList from "./PeriodList.mjs";
import * as PremiseContainer from "./PremiseContainer.mjs";

let match = Tilia.signal("month");

let signal = match[0];

let Unit_set = match[1];

let Unit = {
  defaultState: "month",
  signal: signal,
  set: Unit_set
};

let main_store = Tilia.carve(param => ({
  config: PremiseContainer.state,
  period_list: param.derived(PeriodList.deriveState),
  unit: Tilia.lift(signal)
}));

export {
  Unit,
  main_store,
}
/* match Not a pure module */
