// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App/App.js";
import * as PremiseContainer from "./State/PremiseContainer.js";
import * as Server from "react-dom/server";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";

function render(url) {
  let appUrl = RescriptReactRouter.dangerouslyGetInitialUrl(url, undefined);
  return PremiseContainer.Config.fetch("a55351b1-1b78-4b6c-bd13-6859dc9ad410").then(config => Promise.resolve({
    executorConfig: config,
    html: Server.renderToString(JsxRuntime.jsx(App.make, {
      initialExecutorConfig: config,
      serverUrl: appUrl
    }))
  }));
}

export {
  render,
}
/* App Not a pure module */
