// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App/App.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import "./tailwind.css"
;

import "react-datepicker/dist/react-datepicker.css"
;

let rootElement = document.querySelector("#root");

if (rootElement == null) {
  console.log("No root element found");
} else {
  Client.hydrateRoot(rootElement, JsxRuntime.jsx(App.make, {}));
}

let rootElement$1 = (rootElement == null) ? undefined : Primitive_option.some(rootElement);

export {
  rootElement$1 as rootElement,
}
/*  Not a pure module */
