// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Inventory from "./Database/Inventory.js";

let server = Bun.serve({
  port: 0,
  fetch: async (_request, _server) => {
    let inventory = await Inventory.getInventoryList();
    let headers = {
      "content-type": "application/json"
    };
    let jsonString = JSON.stringify(inventory);
    let body = jsonString !== undefined ? jsonString : "[]";
    return new Response(body, {
      status: 200,
      headers: headers
    });
  }
});

let port = server.port.toString();

let hostName = server.hostname;

console.log(`Server listening on http://` + hostName + `:` + port + `!`);

export {
  server,
  port,
  hostName,
}
/* server Not a pure module */
