// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Premise from "./Database/Premise.js";
import * as Inventory from "./Database/Inventory.js";
import * as Connection from "./Database/Connection.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let get = async (req, param) => {
  let headers = new Headers();
  headers.set("content-type", "application/json");
  let response = await Connection.withClient(async client => {
    let premise_id = req.params["premise_id"];
    let premise = await Premise.getPremise(client, premise_id);
    let inventory = await Inventory.getInventoryList(client, premise_id);
    return {
      inventory: inventory,
      premise: premise
    };
  });
  return Response.json(response, {
    status: 200,
    headers: Primitive_option.some(headers)
  });
};

let handler_GET = get;

let handler = {
  GET: handler_GET
};

let Config = {
  get: get,
  handler: handler
};

let Route = {
  Config: Config
};

let server = Bun.serve({
  port: 8899,
  fetch: async (param, param$1) => new Response("Not Found"),
  routes: Object.fromEntries([[
      "/config/:premise_id",
      handler
    ]])
});

let port = server.port.toString();

let hostName = server.hostname;

console.log(`Server listening on http://` + hostName + `:` + port + `!`);

export {
  Route,
  server,
  port,
  hostName,
}
/* server Not a pure module */
