// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Premise from "./Database/Premise.js";
import * as MockData from "./MockData/MockData.js";
import * as Inventory from "./Database/Inventory.js";
import * as Connection from "./Database/Connection.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let get = async (_req, param) => new Response("hello");

let handler_GET = get;

let handler = {
  GET: handler_GET
};

let Frontend = {
  get: get,
  handler: handler
};

let get$1 = async (req, param) => {
  let headers = new Headers();
  headers.set("content-type", "application/json");
  let response = await Connection.withClient(async client => {
    let premise_id = req.params["premise_id"];
    let premise = await Premise.getPremise(client, premise_id);
    let inventory = await Inventory.getInventoryList(client, premise_id);
    return {
      inventory: inventory,
      premise: premise
    };
  });
  return Response.json(response, {
    status: 200,
    headers: Primitive_option.some(headers)
  });
};

let handler_GET$1 = get$1;

let handler$1 = {
  GET: handler_GET$1
};

let Config = {
  get: get$1,
  handler: handler$1
};

let post = async (req, param) => {
  let premise_id = req.params["premise_id"];
  await Connection.withClient(async client => await MockData.createMockData(client, premise_id));
  return new Response("");
};

let handler_POST = post;

let handler$2 = {
  POST: handler_POST
};

let Inventory$1 = {
  post: post,
  handler: handler$2
};

let Route = {
  Frontend: Frontend,
  Config: Config,
  Inventory: Inventory$1
};

let server = Bun.serve({
  port: 8899,
  fetch: async (param, param$1) => new Response("Not Found"),
  routes: Object.fromEntries([
    [
      "/",
      handler
    ],
    [
      "/config/:premise_id",
      handler$1
    ],
    [
      "/inventory/:premise_id",
      handler$2
    ]
  ])
});

let port = server.port.toString();

let hostName = server.hostname;

console.log(`Server listening on http://` + hostName + `:` + port + `!`);

export {
  Route,
  server,
  port,
  hostName,
}
/* server Not a pure module */
