// Generated by ReScript, PLEASE EDIT WITH CARE


let event_url = "/_events";

let premise_routes = {
  hd: "/item",
  tl: /* [] */0
};

export {
  event_url,
  premise_routes,
}
/* No side effect */
