// Generated by ReScript, PLEASE EDIT WITH CARE


let cart_url = "/cart";

let event_url = "/_events";

let system_routes_1 = {
  hd: event_url,
  tl: /* [] */0
};

let system_routes = {
  hd: cart_url,
  tl: system_routes_1
};

let premise_routes = {
  hd: "item",
  tl: /* [] */0
};

export {
  cart_url,
  event_url,
  premise_routes,
  system_routes,
}
/* No side effect */
